version: '3.7'
services:
  apache:
    build: .docker/apache
    container_name: sortir.com_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/root/sortir.com:cached
    depends_on:
      - php
    networks:
      - mysql_network

  php:
    build: .docker/php
    container_name: sortir.com_php
    volumes:
      - .:/home/root/sortir.com:cached
    external_links:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true

